import type { Product } from "@/lib/types"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Lakers #23 LeBron James Jersey",
    description:
      "Official NBA Lakers jersey featuring LeBron James #23. Made with premium materials for comfort and durability. This authentic jersey features the same design worn by players on the court, with moisture-wicking technology and reinforced stitching.",
    price: 89.99,
    originalPrice: 119.99,
    images: [
      "LAL+MNK+DF+SWGMN+JSY+ASC+22.avif",
      "LAL+MNK+DF+SWGMN+JSY+ASC+22.avif",
      "LAL+MNK+DF+SWGMN+JSY+ASC+22.avif",
    ],
    category: "basketball",
    team: "Los Angeles Lakers",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    isOnSale: true,
    rating: 4.8,
    reviewCount: 156,
    stock_quantity: 25,
    quantity: 1,
  },
  {
    id: "2",
    name: "Warriors #30 Stephen Curry Jersey",
    description:
      "Golden State Warriors official jersey featuring Stephen Curry #30. Perfect for game day or casual wear. Features the team's iconic colors and premium construction.",
    price: 94.99,
    images: ["Stephen curry.png", "Stephen curry.png"],
    category: "basketball",
    team: "Golden State Warriors",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.9,
    reviewCount: 203,
    stock_quantity: 18,
    quantity: 1,
  },
  {
    id: "3",
    name: "Cowboys #4 Dak Prescott Jersey",
    description:
      "Dallas Cowboys official NFL jersey featuring Dak Prescott #4. Show your team spirit with this authentic jersey made from high-quality materials.",
    price: 79.99,
    images: ["200710039_White_BCK.webp", "200710039_White_BCK.webp"],
    category: "football",
    team: "Dallas Cowboys",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.7,
    reviewCount: 89,
    stock_quantity: 32,
    quantity: 1,
  },
  {
    id: "4",
    name: "Patriots #12 Tom Brady Jersey",
    description:
      "New England Patriots legendary Tom Brady #12 jersey. A must-have for any Patriots fan. This iconic jersey represents one of the greatest quarterbacks in NFL history.",
    price: 99.99,
    originalPrice: 129.99,
    images: ["mens-nike-tom-brady-red-new-england-patriots-retired-player-alternate-game-jersey_pi5342000_altimages_ff_5342956-3d9d9a94311c6295859ealt3_full.jpg", "mens-nike-tom-brady-red-new-england-patriots-retired-player-alternate-game-jersey_pi5342000_altimages_ff_5342956-3d9d9a94311c6295859ealt3_full.jpg"],
    category: "football",
    team: "New England Patriots",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    isOnSale: true,
    rating: 4.9,
    reviewCount: 312,
    stock_quantity: 15,
    quantity: 1,
  },
  {
    id: "5",
    name: "Yankees #99 Aaron Judge Jersey",
    description:
      "New York Yankees Aaron Judge #99 jersey. Official MLB merchandise with premium quality. Perfect for baseball fans and collectors alike.",
    price: 84.99,
    images: ["Yankee.png", "Yankee.png"],
    category: "baseball",
    team: "New York Yankees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.6,
    reviewCount: 127,
    stock_quantity: 28,
    quantity: 1,
  },
  {
    id: "6",
    name: "Dodgers #50 Mookie Betts Jersey",
    description:
      "Los Angeles Dodgers Mookie Betts #50 jersey. Perfect for baseball fans and collectors. Features authentic team colors and professional-grade construction.",
    price: 79.99,
    images: ["Mookie.png", "Mookie.png"],
    category: "baseball",
    team: "Los Angeles Dodgers",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.5,
    reviewCount: 98,
    stock_quantity: 22,
    quantity: 1,
  },
  {
    id: "7",
    name: "Manchester United #7 Cristiano Ronaldo Jersey",
    description:
      "Manchester United Cristiano Ronaldo #7 jersey. Official Premier League merchandise featuring the legendary player's iconic number.",
    price: 89.99,
    images: ["CristanoRonaldo.png", "CristanoRonaldo.png"],
    category: "soccer",
    team: "Manchester United",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.8,
    reviewCount: 245,
    stock_quantity: 19,
    quantity: 1,
  },
  {
    id: "8",
    name: "Barcelona #10 Lionel Messi Jersey",
    description:
      "FC Barcelona legendary Lionel Messi #10 jersey. A classic piece for any soccer fan. This jersey represents one of the greatest players of all time.",
    price: 94.99,
    originalPrice: 114.99,
    images: ["LionelMessi.png", "LionelMessi.png"],
    category: "soccer",
    team: "FC Barcelona",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    isOnSale: true,
    rating: 4.9,
    reviewCount: 387,
    stock_quantity: 12,
    quantity: 1,
  },
  {
    id: "9",
    name: "Chiefs #15 Patrick Mahomes Jersey",
    description:
      "Kansas City Chiefs Patrick Mahomes #15 jersey. Official NFL merchandise featuring the Super Bowl champion quarterback.",
    price: 104.99,
    images: ["/placeholder.png?height=600&width=600", "/placeholder.png?height=600&width=600"],
    category: "football",
    team: "Kansas City Chiefs",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.7,
    reviewCount: 178,
    stock_quantity: 24,
    quantity: 1,
  },
  {
    id: "10",
    name: "Celtics #0 Jayson Tatum Jersey",
    description:
      "Boston Celtics Jayson Tatum #0 jersey. Official NBA merchandise featuring one of the league's rising stars.",
    price: 92.99,
    images: ["/placeholder.png", "/placeholder.png"],
    category: "basketball",
    team: "Boston Celtics",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.6,
    reviewCount: 134,
    stock_quantity: 31,
    quantity: 1,
  },
]
